incuna/django-user-management

- CHANGELOG.md
- user_management/api/serializers.py
- user_management/api/tests/test_views.py
Following #92 and regarding the django authenticate method it would help to change the [`ValidateEmailMixin`](https://github.com/incuna/django-user-management/blob/f3ec4d81d7cad37ac6ebb0860a1aa1331740662e/user_management/api/serializers.py#L17) to use `get_by_natural_key` to check if an user exists on registration.
> Use `get_by_natural_key` for `ValidateEmailMixin`

- CHANGELOG.md
- user_management/api/serializers.py
- user_management/api/tests/test_serializers.py
- user_management/api/tests/test_throttling.py
- user_management/api/tests/test_urls.py
- user_management/api/tests/test_views.py
- user_management/api/throttling.py
- user_management/api/urls/register.py
- user_management/api/views.py
If the link to confirm a registration hasn't been clicked after x days it
becomes invalid.
(about the email field).
error (about the email field).
send a new email validation link.
> Add a view to resend a confirmation email.

- CHANGELOG.md
- user_management/api/tests/test_views.py
- user_management/api/views.py
When submitting an expired or a non valid code to `VerifyAccountView` and `PasswordReset` we are currently returning a [`404`](https://github.com/incuna/django-user-management/blob/bf6a967d038c037376fa19f34bf712155dcca11a/user_management/api/views.py#L154). Returning another code would help to determine that the uidb64/token is not valid anymore.
> Return another HTTP code when the token and uidb64 are not valid

- CHANGELOG.md
- user_management/api/exceptions.py
- user_management/api/tests/test_exceptions.py
- user_management/api/tests/test_views.py
- user_management/api/views.py
Related to #98 where a 401 was implemented
> Return HTTP Bad Request 400 code when the token and uidb64 are not valid

- user_management/api/serializers.py
- user_management/api/tests/test_views.py
- user_management/api/views.py
The server returns a token, but when using the token in a request it will return a `401`.
> User can log in to unverified account

- README.md
The AUTH_TOKEN_MAX_AGE, AUTH_TOKEN_MAX_INACTIVITY appear to be seconds in the code but are described as milliseconds
> Update AUTH setting description

- user_management/models/admin_forms.py
- user_management/models/tests/test_admin_forms.py
```python
user_management/models/admin_forms.py:62:
RemovedInDjango18Warning:
Creating a ModelForm without either the 'fields' attribute or the 'exclude'
attribute is deprecated - form UserChangeForm needs updating
class UserChangeForm(forms.ModelForm):
```
> ModelForm deprecation warning

- CHANGELOG.md
- user_management/models/admin_forms.py
- user_management/models/tests/test_admin_forms.py
* The `User` model may have an arbitrary combination of fields based on
the mixins used, and any extra fields added by the project.
> Correct `fields` on `UserChangeForm`

- CHANGELOG.md
- setup.py
- user_management/api/templates/user_management/account_validation_email.html
- user_management/api/templates/user_management/account_validation_email.txt
- user_management/api/templates/user_management/password_reset_email.html
- user_management/api/templates/user_management/password_reset_email.txt
- user_management/api/tests/test_views.py
- user_management/api/views.py
- user_management/models/mixins.py
- user_management/models/tests/models.py
- user_management/models/tests/notifications.py
- user_management/models/tests/test_models.py
- user_management/utils/notifications.py
It looks like we have two different behaviors to send emails in `django-user-management`.
In [some](https://github.com/incuna/django-user-management/blob/be3ca0a4c63b0221e16659800c90831d69781978/user_management/api/views.py#L85) [places](https://github.com/incuna/django-user-management/blob/be3ca0a4c63b0221e16659800c90831d69781978/user_management/api/views.py#L238) we are sending html and text emails and in [`PasswordReset`](https://github.com/incuna/django-user-management/blob/be3ca0a4c63b0221e16659800c90831d69781978/user_management/api/views.py#L133-L140) we only send html emails.
Using `incuna-pigeon` would make sending emails behaving the same accross the project and would allow apps using `django-user-management` to customise handlers to send emails.
As this project is compatible …
> Add `incuna-pigeon` to send notifications

- .travis.yml
`tox` v1.9.1 raises an error when doing a pip install, it looks like
`deps` not installed are translated to `None` instead of being dropped from
the list.
> Pin tox to 1.9.0

- user_management/api/views.py
Adding docstrings for view would allow to use the browsable api from the `djangorestframework`
> Add docstrings for views

- CHANGELOG.md
- docs/mixins.md
- user_management/api/serializers.py
- user_management/api/tests/test_serializers.py
- user_management/api/tests/test_views.py
- user_management/api/views.py
- user_management/models/admin.py
- user_management/models/mixins.py
- user_management/models/tests/test_admin.py
- user_management/models/tests/test_models.py
The variable `User.email_verification_required` is named based upon the presumption that email verification is required when it is possible, and becomes a confusing variable name when applied outside of this context.
Instead of modelling this presumption, we should instead be representing the raw information in the database. To that end, I propose that we rename the boolean to `email_verified`, as that better represents the information that we need to store.
This will require a migration of the values, as when `email_verified==True`, `email_verification_required==False` and vice versa.
> Rename email_verification_required to email_verified

- CHANGELOG.md
- user_management/api/templates/user_management/account_validation_email.html
- user_management/api/templates/user_management/account_validation_email.txt
- user_management/api/tests/test_urls.py
- user_management/api/tests/test_views.py
- user_management/api/urls/verify_email.py
- user_management/api/views.py
- user_management/models/mixins.py
- user_management/models/tests/test_models.py
- user_management/utils/notifications.py
A user can validate its email in two different ways:
* before being able to log in
* after having logged in
The project uses `django.contrib.auth.tokens.default_token_generator` for both resetting and validating emails. 
When the user needs or validates its email before logging in, everything work as expected however once the user is logged in the validation is failing as `PasswordResetTokenGenerator` checks the token against the user last login.
I think it will be probably better to use something else to check the user emai like [django signing](https://docs.djangoproject.com/en/1.7/topics/signing/).
> Untie password confirmation from email verification

- CHANGELOG.md
- user_management/api/permissions.py
- user_management/api/tests/test_throttling.py
- user_management/api/tests/test_views.py
- user_management/api/views.py
In case the user can login but requires to have another confirmation email sent we should be able to do so. I think adding [`AllowAny`](https://github.com/incuna/django-user-management/blob/7da40f402e6e5c678f09de99ea172d2cac94f2f9/user_management/api/views.py#L304) should be enough. We can rely on frontend to send the email of the current user.
> ResendConfirmationEmail should allow anonymous and logged in user

- user_management/api/tests/test_views.py
related to https://github.com/incuna/django-user-management/pull/123#issuecomment-108391219
`last_login` sets to now or None is covered in django
> Remove legacy assert

- CHANGELOG.md
From https://github.com/incuna/django-user-management/pull/129.
@meshy here you go :)
> Update CHANGELOG.md for v8.1.1

- CHANGELOG.md
- user_management/api/serializers.py
If in a project we define a tuple of core fields and try to concatenate
them with the original serializer fields we need to add an exception to
`RegistrationSerializer`.
Making all fields a tuple allow to subclass them more easily.
> Make all fields a tuple in serializers

- CHANGELOG.md
- user_management/api/tests/test_views.py
- user_management/api/views.py
[By default](https://github.com/django/django/blob/0e925de245a0a1bf5d063c816c8bff9f0280a4c7/django/core/signing.py#L134) `signing.loads` has `max_age` sets to `None` which makes the
token to validate an account to never expire.
> Make token expires for AccountVerifyView

- CHANGELOG.md
- setup.py
- user_management/api/authentication.py
- user_management/api/avatar/serializers.py
- user_management/api/serializers.py
- user_management/api/tests/test_authentication.py
- user_management/api/tests/test_throttling.py
- user_management/api/views.py
@incuna/backend merge please? :)
> Swap request.DATA for request.data

- user_management/api/serializers.py
"Your password has not changed" might imply there was an error changing your password, rather than you didn't change it.
@incuna/frontend please review
> Clarify new password error message

- user_management/api/tests/test_views.py
- user_management/api/views.py
- user_management/utils/tests/test_views.py
- user_management/utils/views.py
Turns out DUM had a `VerifyAccountView` in it after all!  This PR splits most of it off into a mixin in order to reimplement the non-API version I added the other day.
> Split the bulk of VerifyAccountView off into a mixin

- user_management/api/avatar/urls/__init__.py
- user_management/api/avatar/urls/user_avatar.py
- user_management/api/urls/__init__.py
- user_management/api/urls/auth.py
- user_management/api/urls/password_reset.py
- user_management/api/urls/profile.py
- user_management/api/urls/register.py
- user_management/api/urls/users.py
- user_management/api/urls/verify_email.py
`patterns` has been removed in 1.10
see https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10
> Remove patterns from urls

- .travis.yml
- requirements.txt
- setup.py
- tox.ini
- user_management/api/tests/test_models.py
- user_management/api/tests/test_throttling.py
- user_management/models/tests/test_models.py
- user_management/tests/run.py
@incuna/backend 
@Minglee01 Get your own back time
> Add django110 to the tests

- CHANGELOG.md
- user_management/ui/tests/test_views.py
- user_management/ui/views.py
Update VerifyUserEmailView to use LOGIN_REDIRECT_URL rather than `/` as the `next` url after the login redirect.
> Remove redirect_to_login from VerifyUserEmailView.

- CHANGELOG.md
- user_management/ui/exceptions.py
- user_management/ui/tests/test_views.py
- user_management/ui/views.py
Redirect to the login when attempting to verify an email address that is already verified.
This avoids presenting the user with a `403 Forbidden` error when the they click the email verification link a second time.
> Redirect to login when email is already verifyed.
