CHANGELOG.md
setup.py
user_management/api/serializers.py
user_management/api/tests/test_serializers.py
user_management/api/tests/test_views.py
user_management/utils/tests/test_validators.py
user_management/utils/validators.py

Add validation for password complexity

---

user_management/utils/validators.py

Makes generating translations easier

Hard-code translatable string

---

.travis.yml
Makefile

Based on the [travis instructions](http://docs.travis-ci.com/user/deployment/pypi/).

Enable package release via travis on tag push

---

.travis.yml

Add a variable to check when to deploy

Release only once on travis

---

CHANGELOG.md
user_management/utils/notifications.py

Fix translations for notifications

---

CHANGELOG.md
user_management/api/templates/user_management/account_validation_email.html
user_management/api/templates/user_management/account_validation_email.txt
user_management/api/templates/user_management/password_reset_email.html
user_management/api/templates/user_management/password_reset_email.txt

Added actual HTML to HTML templates.
Removed unnecessary spaceless and autoescape tags.
@incuna/backend please review

Updated HTML templates

---

.travis.yml

Attempt to fix travis tests

---

CHANGELOG.md
user_management/api/serializers.py

And allow them to be translatable

Add email labels for 'RegistrationSerializer' and 'UserSerializerCreate'

---

.travis.yml
CHANGELOG.md
user_management/api/avatar/tests/test_views.py
user_management/api/serializers.py
user_management/api/tests/test_serializers.py
user_management/api/tests/test_views.py

Backporting in some fixes from later versions to v8.1.x.

Improve new-password validation errors

---

.travis.yml
tox.ini
user_management/models/tests/factories.py
user_management/ui/tests/test_views.py
user_management/ui/views.py

We use this sort of view all over the place, probably about time we put it in a library.  (Turns out #69 agrees with me.)  On @maxpeterson's suggestion I put it under a folder called `ui`, to contrast with `api`.
@incuna/backend review please? :)

Add VerifyUserEmailView

---

user_management/api/tests/urls.py
user_management/tests/run.py
user_management/ui/tests/test_urls.py
user_management/ui/urls.py

@incuna/backend quick review please? :)

Add a URL for VerifyUserEmailView

---

.travis.yml
Makefile

@incuna/backend merge please? :)

Add `make release`

---

user_management/api/tests/test_views.py
user_management/api/views.py
user_management/ui/exceptions.py
user_management/ui/tests/test_exceptions.py
user_management/ui/tests/test_views.py
user_management/ui/views.py
user_management/utils/tests/test_views.py
user_management/utils/views.py

Use VerifyEmailViewMixin for the UI version of the view

---

user_management/ui/tests/test_urls.py
user_management/ui/urls.py

Was somehow missed in the refactor and tests didn't catch it.
@incuna/backend merge please?

Fix URL for VerifyUserEmailView

---

CHANGELOG.md
setup.py
user_management/api/tests/test_views.py
user_management/models/tests/notifications.py
user_management/models/tests/test_models.py
user_management/utils/notifications.py

@incuna/backend Please review.

Add `headers` to `utils.email_handler`.

---

user_management/ui/tests/test_views.py
user_management/ui/views.py

- Ensure the success message shows up.
- Redirect to the login page rather than to /.

Fix redirect after confirming your email address

---

user_management/api/tests/test_views.py
user_management/utils/notifications.py

Add settings to change email subjects

---

.travis.yml
tox.ini

Passing locally (except the ones that are ignored...)
@incuna/backend

Added py35 to the tests

---

.coveragerc
Makefile
requirements.txt
setup.cfg

This involves upgrading `coverage`. Please review!
Edit: obviously, there's no need for a release of this -- it's only for testing `:)`

Hide covered files from coverage report

---

CHANGELOG.md
requirements.txt
user_management/ui/tests/test_views.py
user_management/ui/views.py

Allow VerifyUserEmailView get_redirect_url to allow an extra string set

---

CHANGELOG.md
user_management/ui/tests/test_views.py
user_management/ui/views.py

Fix https://opbeat.com/incuna/myday-live/errors/32/

Fix bug using VERIFIED_QUERYSTRING with a LOGIN_URL
